server:
  port: 8040
spring:
  application:
    name: gateway
#  zipkin:
#    base-url: http://localhost:9411/
#    discoveryClientEnabled: false
#  sleuth:
#    sampler:
#      # \u62BD\u6837\u7387\uFF0C\u9ED8\u8BA4\u662F0.1\uFF0810%\uFF09
#      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 148.70.34.49:8848
    gateway:
      discovery:
        locator:
          # \u8BA9gateway\u901A\u8FC7\u670D\u52A1\u53D1\u73B0\u7EC4\u4EF6\u627E\u5230\u5176\u4ED6\u7684\u5FAE\u670D\u52A1
          enabled: true
      routes:
      - id: user_route
        uri: lb://user-center
        predicates:
        - Path=/users/**
      - id: content_route
        uri: lb://content-center
        predicates:
        - Path=/shares/**,/admin/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: trace
